### PR TITLE
push launch back 2 weeks

### PR DESCRIPTION
**Pull request by crappyrules**
change launch date.  actual date tbd

### CODE REVIEW

**Comment by donuts-are-good** [comment]
Please do January 9

**Comment by crappyrules** [comment]
I just came across some other stuff I wanted to change too.  I just wanted to throw this up now before I can dive into the other stuff later tonight or tomorrow because a couple people hit me up today about the launch countdown.  I'll get them all put together and put in a new pr

**Comment by donuts-are-good** [comment]
before milestone 1 and 2 we should add:

- web extension (new milestone 2)

- gui wallet (new milestone 3)


image

**Comment by donuts-are-good** [comment]
This is just an additive change

**Pull request closed without merging**
